### ISSUE TITLE
Require a save directory?

### ISSUE THREAD

**Issue by manuelhaussmann** [nasimrahaman/inferno#28]
Several parts of the Trainer class require a location to save to but don't complain until it is too late. 
Examples are (of course) when a save point is specified via save_every, but the trainer also defaults to saving after a validation run even without a necessary directory.

**Comment by nasimrahaman** [comment]
Agreed, this should be handled better.

**Comment by nasimrahaman** [comment]
Had another look, and you're right that [this](https://github.com/nasimrahaman/inferno/blob/e846592e5a660d972ab6eeaf46cb92656f88c792/inferno/trainers/basic.py#L81) should definitely default to False.

**Comment by nasimrahaman** [comment]
Fixed in master, thanks!
