### ISSUE TITLE
Clean up tests and set up Travis CI

### ISSUE THREAD

**Issue by nasimrahaman** [nasimrahaman/inferno#31]
- [ ] Some tests require GPU, and they need to be `unittest.skip`-ped. 
- [x] Need more travis-friendly tests for `Trainer`, perhaps with a dummy model on a dummy dataset with a dummy criterion and a dummy metric.

**Comment by DerThorsten** [comment]
Might be easier to fix with https://github.com/nasimrahaman/inferno/pull/34

**Comment by nasimrahaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Travis Tests](https://trello.com/c/ujNOdfOx/3-travis-tests)

**Comment by nasimrahaman** [comment]
Done, thanks to @DerThorsten.
