### ISSUE TITLE
Uniitests to agressive

### ISSUE THREAD

**Issue by DerThorsten** [nasimrahaman/inferno#52]
@nasimrahaman  I think the unit tests are to aggressive.

They tend to fail too often on travis.
I guess one should relax these tests a bit
```
self.assertLess(trainer.get_state('validation_error_averaged'), (1 - 1/self.NUM_CLASSES))
E       AssertionError: 0.9244186046511628 not less than 0.9
```

**Comment by nasimrahaman** [comment]
Agreed. In general, we need more sensible integration test involving serialization.
